### ISSUE TITLE
Simple media skill gives error

### ISSUE THREAD

**Issue by piretro999** [ejstacey/skill-subsonic-media#3]
Hello, it seems that if I cast the play command it does not work. Insterad it gives me this message: "An error occoured while processing a request in Simple Media Skill".
I don't know if this can depend on the fact that I use the Mark 1 or that I use Madsonic instead of Subsonic.

**Comment by piretro999** [comment]
Hi, the madsonic site reports that: "All the Madsonic apps are built using the Madsonic/Subsonic REST API."
So it seems not an API problem.
when I say cast, I mean play,...I am not sure how could I play on chromecast using the Mark 1.
Here I report what happens when I tell Mycroft Mark 1 to play (using the text client)


 play la copa de la vida by ricky                           DEBUG output
 martin on vlc                                                       mycroft-skills.log, oth
 >> An error occurred while processing               mycroft-speech-client.l
    a request in Simple Media Skill
 play on vlc                                                           --- 192.34
 >> An error occurred while processing
    a request in Simple Media Skill

**Comment by piretro999** [comment]
08:16:09.247 - mycroft.skills.core:wrapper:609 - ERROR - An error occurred while processing a request in Simple Media Skill
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/skills/core.py", line 600, in wrapper
handler(message)
File "/opt/mycroft/skills/mycroft-skill-simple-media-controls/__init__.py", line 103, in handle_play_intent
self.run_cmd("play")
File "/opt/mycroft/skills/mycroft-skill-simple-media-controls/__init__.py", line 84, in run_cmd
self.speak_dialog("missing.config.command", spec)
File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/skills/core.py", line 876, in speak_dialog
self.speak(self.dialog_renderer.render(key, data), expect_response)
File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/dialog/__init__.py", line 87, in render
line = line.format(**context)
KeyError: u'cmd'
08:16:09.250 - SKILLS - DEBUG - {"data": {"name": "SimpleMediaSkill.handle_play_intent"}, "type": "mycroft.skill.handler.start", "context": null}
08:16:09.255 - SKILLS - DEBUG - {"data": {"expect_response": false, "utterance": "An error occurred while processing a request in Simple Media Skill"}, "type": "speak", "context": {"target": null}}
08:16:09.300 - SKILLS - DEBUG - {"data": {"exception": "cmd", "name": "SimpleMediaSkill.handle_play_intent"}, "type": "mycroft.skill.handler.complete", "context": null}
08:16:09.324 - SKILLS - DEBUG - {"data": {}, "type": "recognizer_loop:audio_output_start", "context": null}
08:16:09.325 - mopidy_skill - INFO - lowering volume
08:16:09.392 - SKILLS - DEBUG - {"data": {}, "type": "Command: mouth.talk", "context": null}
08:16:09.895 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/2bc1d62d-68ff-485a-9df3-93894a6ee7f7/metric/timing HTTP/1.1" 200 269
08:16:10.328 - SKILLS - DEBUG - {"data": {}, "type": "1017122086:TimeSkillupdate_display", "context": null}
08:16:13.890 - SKILLS - DEBUG - {"data": {}, "type": "recognizer_loop:audio_output_end", "context": null}
08:16:13.891 - mopidy_skill - INFO - maybe restoring volume
08:16:13.939 - SKILLS - DEBUG - {"data": {}, "type": "Command: mouth.reset", "context": null}

**Comment by ejstacey** [comment]
It looks like mopdiy skill is stepping in instead of the Subsonic Skill.  This is possibly the same issue we see with #4, which is a bigger issue Mycroft needs to handle.  In the meantime, I've added functionality for saying "sub play <whatever>" instead of "play <whatever>".  This should prevent other skills taking over and getting int he way.  Can you please give it a shot with "sub play la copa de la vida by ricky"?

Thanks!

**Comment by piretro999** [comment]
Hi, I already tried that and it still does the same behaviour. I have right now a doubt: I am using a Mark1 and not a generic linux hardware, nor a generic raspbian. 
Moreover it still does not appears into the msm list.
Maybe this app is only suitable for a pc?
Thank you
Paolo

**Comment by ejstacey** [comment]
I was thinking it would work fine on the mark1, then I spent like 10 hours reimaging my mark1 constantly and trying to make it work.  I haven't gotten it going yet.

For not showing up in MSM, Kathy Reid from Mycroft just posted a blog today explaining why that would be happening: https://mycroft.ai/blog/skill-branching-18-02/

Basically, it's because the mark1 image is a certain point in time, and doesn't update automatically, it seems.  The skills repo is also set to that specific point in time (via a branch).  I need to do a pull request to get my skill listed in the 18.02-branch skills repo... but I need to get it working on that version mycroft-core first.

So: I am reopening this, and I will definitely keep working on getting this going properly on the current production version of mark1 (18.02, from Feb), but it may be a little while.
